### ISSUE TITLE
Reloadium experienced a fatal error and has to quit.

### ISSUE THREAD

**Issue by ericmock** [reloadware/reloadium#150]
Very similar to: https://github.com/reloadware/reloadium/issues/76#issue-1472779069

Except:  using Python 3.10 on Manjaro with a local project and the cakeshop.py "calculate" example.

**Comment by dkrystki** [comment]
@ericmock Could you provide more info?

## Describe the bug*
A clear and concise description of what the bug is.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Desktop or remote (please complete the following information):**
 - OS: [e.g. Windows]
 - OS version: [e.g. 22]
 - M1 chip: [yes/no]
 - Reloadium package version: [e.g 0.8.6]
 - PyCharm plugin version: [e.g 0.8.0 or None]
 - Editor: [e.g PyCharm]
 - Python Version: [eg. 3.9.1]
 - Python Architecture: [eg. 32bit, 64bit]
 - Run mode: [e.g Run/Debug]


## Additional context
Add any other context about the problem here.

**Comment by dkrystki** [comment]
Also could you run it again with environmental variable set to `RW_DEBUG=True`?

**Comment by ericmock** [comment]
The debug information ended with:  RecursionError: maximum recursion depth exceeded in comparison

**Comment by dkrystki** [comment]
@ericmock 
I can't reproduce this. 
Is it the whole traceback? 

Also could you share the code around line 148 in feature.py?

**Comment by ericmock** [comment]
Restarting PyCharm (again?) seems to have fixed the issue.
