### ISSUE TITLE
Reloadium 1.0.1 obsolete

### ISSUE THREAD

**Issue by JelleWeigand** [reloadware/reloadium#157]
We are using Reloadium 1.0.1 in our Python 3.7 project. We are not using the plugin and run it via the command line. This was fine up until this morning when we started receiving the 'obsolete' error. We would like to upgrade to a newer version of Reloadium, but the newer versions have dropped support for Python 3.7. We are not able to switch to a newer version of Python due to other implications. Therefore, we would like to continue using Reloadium 1.0.1.

Is there a way to bypass the 'obsolete' check?

**Comment by dkrystki** [comment]
@JelleWeigand unfortunatelly there is no way to bypass this check. I have limited resources to maintain this project at this moment so the older versions are made obsolete to not overload Sentry.

**Comment by veylonni** [comment]
Hi @dkrystki and thanks a lot for this tool ! I have this 'obsolete error' and I can't easily update often to keep up with new releases...
I don't understand how this 'obsolete' error can magically appear when PyCharm, Reloadium Plugin, nor Python aren't upgraded.
Could you please enlighten me on this point? Thx

**Comment by dkrystki** [comment]
Hi @veylonni, the 'obsolete' error appears 4 months after a release, as the date is embedded in the Reloadium package. 
This approach helps manage the limited Sentry quota, which may get exhausted if a buggy release sticks around for too long. Currently, our sponsorship funds aren't sufficient to cover higher quotas that's why I'm working on monetizing Reloadium to afford tools like Sentry and maintain high quality of the code. 
Visit this page to learn more https://reloadium.io/pricing
