### ISSUE TITLE
Question about logging and telemetry

### ISSUE THREAD

**Issue by avirshup** [reloadware/reloadium#31]
Hi - why does this software connect to "depot.reloadware.com" when it runs? Worryingly, I don't see any source code in this repository that would make such a connection. How did this behavior make it into the PyPI wheel?

Also, I see it's trying to upload logs to sentry.io from my machine. Why? What information is being sent from my machine? How is it stored? Is it anonymized?

This is with Python 3.10.6, Reloadium 0.9.1, on Linux, installed via the PyPI manylinux wheel.

**Comment by dkrystki** [comment]
Hi, reloadium uses sentry.io and django backend (depot.reloadware.com) for logging and error reporting.
The reason why sentry is used is to make sure errors on startup are also reported. Nothing else is sent using sentry (as far as I know. I'll confirm that later)

Information that is being sent is standard error reporting and diagnostic data like python version, os version, time etc.
Paths, function names etc are fully anonymized if present.

Part of the python code is not opensourced (java and javascript part are fully opensourced). I explained why here https://github.com/reloadware/reloadium/issues/27

Error reporting is the industry standard and without it it would be pretty much impossible to improve or make this project stable.
Having a way to opt out would be nice though and I'll add an env variable to control that in the next release.

I'll also add a section in the documentation what is exactly being logged (it's not technically needed since no personal data is processed but I want to be transparent here).

P.S. I've change the title since the network calls are not obfuscated (unless you're talking about https?)

**Comment by dkrystki** [comment]
Added opting out in reloadium 0.9.2 (PyCharm plugin 0.8.5) 
More about what is collected:
https://reloadium.io/legal/privacy-policy
