### ISSUE TITLE
[Feature Request] Need reloadium to work without manually adding breakpoints

### ISSUE THREAD

**Issue by James4Ever0** [reloadware/reloadium#61]
**Describe the bug**

Suppose there's some bug in my code. I don't know where and I don't know why. I only know this by running code for 4 hours and I need reloadium to pinpoint its location for me to edit and reload the code without restarting. Exceptions wrapped in `try...except` are ignored. Only those raised without being caught will trigger this behavior. The breakpoint should not go beyond the scope if configured. If the scope is limited to current folder, files outside this folder shall not be traced and breakpoint level is limited to the root cause of the exception in this folder.

**To Reproduce**

1. Run a program with reloadium without adding breakpoints
2. Reloadium raises an exception
3. Program exits

**Expected behavior**

Reloadium will not exit, automatically generate breakpoint at the location where exception is raised, letting me to fix it.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 12.5
 - Reloadium package version: 0.9.4
 - PyCharm plugin version: None
 - Editor: PyCharm CE
 - Run mode: Debug

**Additional context**

Example scenario:

```python

def trouble():
    raise Exception('error!') # reloadium should automatically add a breakpoint here after running without exiting.

if __name__ == "__main__":
    # long and tedious startup omitted.
    trouble()
```

**Comment by dkrystki** [comment]
This has always been working. See gif below
![dynamic_breakpoints](https://user-images.githubusercontent.com/45499236/200764555-2d3b1c80-a277-478e-8ae9-67075178a8b6.gif)

**Comment by dkrystki** [comment]
@James4Ever0 
I think it's a great idea. 
Definitely would like that be added but have to see if it's feasible to implement.

**Comment by James4Ever0** [comment]
Similar capabilities have been achieved by [my modified version of reloading](https://github.com/James4Ever0/reloading)

Use against this code:

```python
from reloading import reloading
import asyncio


@reloading
class mClass:
    someValue = 2

    @reloading
    def someMethod(self):
        @reloading
        def someInnerMethod():
            raise Exception("exception1")
            return "inside function return"

        raise Exception("exception2")
        val = someInnerMethod()
        return val

    @reloading
    async def someOtherMethod(self):
        # raise Exception('async exception1')
        @reloading
        async def asyncInside():
            raise Exception("async exception2")
            return "async inside return"

        val = await asyncInside()
        return val

    @reloading
    def runAsync(self):
        loop = asyncio.get_event_loop()
        val = loop.run_until_complete(self.someOtherMethod())
        print("value from async func:", val)
        return val


@reloading
def main():
    MClass = mClass()
    print(MClass)
    val = MClass.someMethod()
    print("return value:", val)
    val = MClass.runAsync()
    print("return async value:", val)
    print("success!")


main()

```

**Comment by James4Ever0** [comment]
[debugpy](https://pypi.org/project/debugpy/) is able to capture 'raised exception' and preserve context.

**Comment by dkrystki** [comment]
I'm trying to implement this and although feasible I stumbled on a UX/Program logic issue.
For the below example it shouldn't halt the execution since the exception will be handled at the call site (line 10).

![2023-01-05_22:18:32](https://user-images.githubusercontent.com/45499236/210778579-a50870b3-b46c-45cb-a142-7147b040b654.png)

I'm trying to figure out how to detected that the exception will be handled in the future while executing the top most frame.
I've been thinking about using some static analysis and exec function to figure out whether the exception will be handled but this seems a bit hacky and potentially very slow.

Any ideas?

**Comment by dkrystki** [comment]
I'm trying to implement this and although feasible I stumbled on a UX/Program logic issue.
For the below example it shouldn't halt the execution since the exception will be handled at the call site (line 11).

![2023-01-05_22:28:40](https://user-images.githubusercontent.com/45499236/210780522-46a074a9-62c2-4a46-bd8e-ad391194795d.png)


I'm trying to figure out how to detected that the exception will be handled in the future while executing the top most frame.
I've been thinking about using some static analysis and exec function to figure out whether the exception will be handled but this seems a bit hacky and potentially very slow.

Any ideas?

**Comment by James4Ever0** [comment]
I use code parser too to handle such nested `try...except` problems. You can check how my [Hy](https://github.com/James4Ever0/hy) interpreter patch works. I leave multiple command line switches for turning on/off features. Notice Hy interpreter only turns Hy code into HyTree, where I do my static analysis job. What I do to handle this "checked exception" or "exception within try block" is by scanning the entire AST twice. At first scan, I mark ranges where covered `try...except` and where not. At second scan, I put another level of `try...except` around those lines not covered by any `try...except`. In your case, you should put breakpoints outside those areas, in which those areas may differ from my case.

**Comment by James4Ever0** [comment]
Talking of speed, I think some filesystem watchdogs plus code stored in Redis will do. Everytime code changes, it shall retrieve latest code from Redis whenever it needs. If no changes were made (changes were reported by watchdogs), no parsing nor code retrieval will be done.

**Comment by dkrystki** [comment]
@James4Ever0 
Thanks for your help. I managed to implement this. 
Would you like to be a beta tester?

**Comment by James4Ever0** [comment]
Yes I would like to.

**Comment by James4Ever0** [comment]
Also I think generators can be tricky to deal with (functions with "yield" keywords). I would do some experiments since I lack such experience.

**Comment by dkrystki** [comment]
Yes, generators can be tricky. They are not tested that well yet.

Thanks for helping out. Send me an email at damian@reloadware.com and I'll add you to our discord channel.

**Comment by James4Ever0** [comment]
Email sent!

**Comment by dkrystki** [comment]
Added in reloadium 0.9.7 and PyCharm plugin 0.9.2
