### ISSUE TITLE
Can't get memory line profiler in PyCharm

### ISSUE THREAD

**Issue by danb27** [reloadware/reloadium#71]
**Describe the bug**
I just downloaded the pycharm plugin for reloadium after seeing it on reddit. Looks like a very useful tool, but I am having trouble replicating the memory line profiling shown in this post (and README doesn't include info on memory profiling yet): https://www.reddit.com/r/pycharm/comments/z0x4gu/memory_profiling_for_pycharm/

Apologies if I am just doing something wrong!

**To Reproduce**
1. Use my code below with breakpoints on each `pass`
2. Debug using reloadium
3. Open profiling details in the margin
4. Details are in units of time, not memory
5. In the Debug tab of pycharm, open the Reloadium sub-tab, change the profiler to "Memory"
6. Nothing changes
7. Repeat steps 2-3, but profiler setting from step 5 resets to Time and details are still in units of time

**Expected behavior**
Should be able to easily switch between units of time/memory, possibly having to rerun the debugger if technically necessary

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop OS (Ubuntu)
 - OS version: 22.04 LTS
 - M1 chip: No
 - Reloadium package version: 0.9.5
 - PyCharm plugin version: 0.9.0
 - Editor: PyCharm
 - Python Version: 2022.2.2 Professional
 - Python Architecture: 64bit
 - Run mode: Debug

**Additional context**
My code:
```
import numpy as np
import pandas as pd


def foo():
    data = np.random.randint(0, 100, size=(10, 1000))
    df = pd.DataFrame(data)
    df = pd.concat([df, df])
    pass


def bar():
    a = b"r" * 10_000
    pass


if __name__ == '__main__':
    foo()
    bar()
```

https://user-images.githubusercontent.com/42096328/203413798-251af93b-c2d4-4df4-adf9-a33ffe569cc7.mov

**Comment by dkrystki** [comment]
Hi @danb27 thanks for making this issue.
UX for this feature is still something I have to work on.

You're getting timing information instead of memory because default profiler is set to time profiler. You can change it dynamically like you have shown but the call stack frame has to be restarted to see memory profiling information.

To change default profiler go to `Reloadium` -> `Preferences` and change `Default profiler` to `Memory`
I'll try collecting both profiling data in the same time so changing it dynamically will work without restarting frame.

**Comment by danb27** [comment]
Ah! There it is. Thank you!
