### ISSUE TITLE
Reloadium experienced a fatal error and has to quit.

### ISSUE THREAD

**Issue by TS9001** [reloadware/reloadium#76]
Hi Reloadium, I have encountered following issue:

## Describe the bug
I would like to use reloadium in order to debug my remote code. Unfortunately, when I click on debug I get the following error:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/44685678/205290701-89ada685-d320-4ea0-a81b-52d594c113c1.png">

## To Reproduce
1. Go to Pycharm and specify remote SFTP deployment, set the local and remote paths correctly
2. Go to Interpreter settings and set the remote ssh interpreter using deployment previously defined
3. Install reloadium by `pip3.8 install reloadium` command.
4. Click on debug in order to test that your debugging works in general, after breakpoint is hit, stop it.
6. Click on reloadium debugging

## Expected behavior
Debugging works as expected, hot-swap is possible.

**Comment by dkrystki** [comment]
Need more info about your remote

## Desktop or remote (please complete the following information):**
 - OS: [e.g. Windows]
 - OS version: [e.g. 22]
 - M1 chip: [yes/no]
 - Reloadium package version: [e.g 0.8.6]
 - Python Version: [eg. 3.9.1]
 - Python Architecture: [eg. 32bit, 64bit]

**Comment by TS9001** [comment]
OS: Linux
OS version: Ubuntu 18.04.6 LTS
M1 chip: No
Reloadium package version: 0.9.0 (I tried changing the version to different-ones, but it did not work)
Python Version: 3.8.15
Python Architecture: 64bit

**Comment by dkrystki** [comment]
Could you confirm 0.9.0 is the python package version https://pypi.org/project/reloadium/ ?
How did you try installing different ones?

**Comment by dkrystki** [comment]
Does it happen even when running simple scripts?

**Comment by dkrystki** [comment]
Unfortunately it's not possible now.
I'll add a flag to enable printing full errors in the next release since it's pretty much impossible to figure out what is going on currently.

**Comment by TS9001** [comment]
Thank you for answer, I was trying to debug it little bit, unfortunately did not found the answer.

**Comment by ericmock** [comment]
Has anything come of this?

PyCharm 2023.1 (Community Edition)
Manjaro

Installed via PyCharm plugin window.  I get this when trying to run the simple "cakeshop.py" example.

**Comment by dkrystki** [comment]
@ericmock could you provide more info?

## Describe the bug*
A clear and concise description of what the bug is.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Desktop or remote (please complete the following information):**
 - OS: [e.g. Windows]
 - OS version: [e.g. 22]
 - M1 chip: [yes/no]
 - Reloadium package version: [e.g 0.8.6]
 - PyCharm plugin version: [e.g 0.8.0 or None]
 - Editor: [e.g PyCharm]
 - Python Version: [eg. 3.9.1]
 - Python Architecture: [eg. 32bit, 64bit]
 - Run mode: [e.g Run/Debug]


## Additional context
Add any other context about the problem here.
