### ISSUE TITLE
Reloadium crashes with SIGSEGV signal

### ISSUE THREAD

**Issue by ChillarAnand** [reloadware/reloadium#99]
## Describe the bug*
When updating a previous function in the stack, reloadium crashes with SIGSEGV signal.

## To Reproduce
Run [this script](https://github.com/ChillarAnand/avilpage.com/blob/master/scripts/dynamic.py) in debug mode.

After the breakpoint is hit, try to change the array values.

## Expected behavior
It shouldn't crash and update the functions.

## Screenshots
<img width="1280" alt="Screenshot 2023-02-06 at 13 30 10" src="https://user-images.githubusercontent.com/4463796/216916611-3d86f6b4-b511-4804-a978-03ca91ecd6be.png">

## Desktop or remote (please complete the following information):**
OS: Mac
OS version: 13.0.1
M1 chip: yes
Reloadium package version: 0.9.10
PyCharm plugin version: 0.9.5
Editor: PyCharm
Python Version: 3.9.12
Python Architecture:64
Run mode: Debug

**Comment by dkrystki** [comment]
It's related to https://github.com/python/cpython/issues/92311
Please upgrade to the newest python 3.9 version

**Comment by dkrystki** [comment]
This is expected behavior since changed  function is not in the call stack so the frames are not dropped.
If you want to see the change you have to drop them manually like in the gif below:
![Peek 2023-02-06 21-56](https://user-images.githubusercontent.com/45499236/216965493-3041281d-f998-4eb5-9e08-0c9e4ca9873e.gif)
